[plottingutilities_theme]
git-tree-sha1 = "b29a308912d28ce69ad708258af184ad1a14c4da"

    [[plottingutilities_theme.download]]
    sha256 = "56d318df8da775015feebe3e9bf3b472d3dd8354460272a4e6da8a32067ab924"
    url = "https://pumas-product-bundles.s3.us-east-1.amazonaws.com/artifacts/PlottingUtilities-0.15.6.tar.gz"
